name: Build project

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2020.3.25f1
          allowDirtyBuild: true

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2020.3.25f1
          targetPlatform: StandaloneWindows64 
          allowDirtyBuild: true

      # Output 
      - uses: actions/upload-artifact@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          name: Build
          path: build

      - name: Zip build
        run: |
          pushd build/StandaloneWindows64
          zip -r ../../StandaloneWindows64.zip .
          popd
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          files: StandaloneWindows64.zip
          name: Release ${{ github.ref }}
